// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Board$ReactTemplate = require("./Board.bs.js");

var component = ReasonReact.statelessComponent("CardView");

function make(handleToggleRevealed, handleEditCard, card, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: Board$ReactTemplate.getClasses(card),
                          onClick: (function (e) {
                              e.preventDefault();
                              return Curry._1(handleToggleRevealed, card[/* id */0]);
                            })
                        }, React.createElement("span", undefined, card[/* word */1]), React.createElement("button", {
                              className: "edit",
                              onClick: (function (e) {
                                  e.stopPropagation();
                                  return Curry._1(handleEditCard, card[/* id */0]);
                                })
                            }, "Edit"));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
