// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Board$ReactTemplate = require("./Board.bs.js");

var component = ReasonReact.statelessComponent("CardView");

function make(handleToggleRevealed, handleEditCard, card, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: Board$ReactTemplate.getClasses(card),
                  onClick: (function (e) {
                      e.preventDefault();
                      return Curry._1(handleToggleRevealed, card[/* id */0]);
                    })
                }, React.createElement("span", undefined, card[/* word */1]), React.createElement("button", {
                      className: "edit",
                      onClick: (function (e) {
                          e.stopPropagation();
                          return Curry._1(handleEditCard, card[/* id */0]);
                        })
                    }, "Edit"));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
