// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function stringify(t) {
  switch (t) {
    case 0 : 
        return "UpdateCard";
    case 1 : 
        return "ToggleRevealed";
    case 2 : 
        return "UpdateBoard";
    
  }
}

var Common = /* module */[/* stringify */stringify];

exports.Common = Common;
/* No side effect */
