// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';


function stringify(t) {
  switch (t) {
    case 0 : 
        return "UpdateCard";
    case 1 : 
        return "ToggleRevealed";
    case 2 : 
        return "UpdateBoard";
    
  }
}

exports.stringify = stringify;
/* No side effect */
