// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("EditCardView");

function make(card, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", {
                  className: "card edit"
                }, React.createElement("input", {
                      placeholder: "Enter word",
                      value: self[/* state */2][/* cardState */0][/* word */1],
                      onChange: (function (e) {
                          var target = e.target;
                          return Curry._1(self[/* send */4], /* ChangeWord */Block.__(0, [target.value]));
                        })
                    }), React.createElement("select", undefined, React.createElement("option", {
                          value: "red"
                        }, "Red"), React.createElement("option", {
                          value: "blue"
                        }, "Blue"), React.createElement("option", {
                          value: "neutral"
                        }, "Neutral"), React.createElement("option", {
                          value: "assassin"
                        }, "Assassin")), React.createElement("button", {
                      type: "submit"
                    }, "Save"));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* cardState */card];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action.tag) {
        var init = state[/* cardState */0];
        return /* Update */Block.__(0, [/* record */[/* cardState : record */[
                      /* id */init[/* id */0],
                      /* word */init[/* word */1],
                      /* cardType */action[0]
                    ]]]);
      } else {
        var init$1 = state[/* cardState */0];
        return /* Update */Block.__(0, [/* record */[/* cardState : record */[
                      /* id */init$1[/* id */0],
                      /* word */action[0],
                      /* cardType */init$1[/* cardType */2]
                    ]]]);
      }
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
