// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("EmptyCardView");

function make(handleEditCard, card, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "card empty",
                  onClick: (function (e) {
                      e.preventDefault();
                      return Curry._1(handleEditCard, card[/* id */0]);
                    })
                });
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
