// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Express = require("bs-express/src/Express.js");
var Process = require("process");

var app = Express.express(/* () */0);

Curry._3(Express.App[/* get */4], app, "/hello", Express.Middleware[/* from */5]((function (_, _$1) {
            var partial_arg = Express.Response[/* sendString */2];
            return (function (param) {
                return partial_arg("hello!!!", param);
              });
          })));

var dirname = typeof (__dirname) === "undefined" ? undefined : (__dirname);

var publicDir = dirname !== undefined ? dirname + "/../build" : "./build";

Curry._2(Express.App[/* use */0], app, Express.Static[/* asMiddleware */4](Express.Static[/* make */3](publicDir, Express.Static[/* defaultOptions */0](/* () */0))));

function onListen(e) {
  var exit = 0;
  var val;
  try {
    val = e;
    exit = 1;
  }
  catch (raw_exn){
    var exn = Js_exn.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      console.log(exn[1]);
      Process.exit(1);
      return /* () */0;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    console.log("Listening at http://localhost:" + String(3333));
    return /* () */0;
  }
  
}

Express.App[/* listen */19](app, /* Some */[3333], /* Some */[onListen], /* () */0);

var port = 3333;

var dirname$1 = dirname === undefined ? /* None */0 : [dirname];

exports.port = port;
exports.app = app;
exports.dirname = dirname$1;
exports.publicDir = publicDir;
exports.onListen = onListen;
/* app Not a pure module */
